### ISSUE TITLE
1.7.0: concurrent modification exception

### ISSUE THREAD

**Issue by JohannesBeranek** [playframework/play1#1405] opened 2022-04-20 14:20 UTC
Play version 1.7.0, DEV mode

Looks to me like the amount of concurrentModificationException encountered in DEV mode suddenly skyrocketed. We only had those very very sparsely before, but with play version 1.7.0 they happen about every 10th request.

Always in ApplicationClasses.getApplicationClass. Maybe classes Map should be replaced with a ConcurrentHashMap / add synchronization ?

**Comment by aleksandy** [comment] 2022-04-24 16:45
Could you provide stacktrace of the exception? 

I assume the cause of ConcurrentModificationException is ```computeIfAbsent()``` that has added in 8fad39b17ef215a43e4185bae32ed9caac011f30. But in my opinion there is no reasons to change map type to concurrent version because in production you use precompiled classes (don't you?) and hashmap will be filled by the all classes before the first concurent request. 

Also thread-unsafe map is good choice for readonly work in multithread env because it has more  performance because it doesn't care about sync.

**Comment by asolntsev** [comment] 2022-04-24 17:06
@aleksandy Yes, we experienced ConcurrentModificationException in DEV mode, but it was also a problem: the application suddenly restarted, sometimes even multiple times.

**Comment by aleksandy** [comment] 2022-04-25 06:26
@asolntsev, looks like we don't have a choice. The map should be changed to ConcurrentHashMap. I've send PR.

**Comment by aleksandy** [comment] 2022-06-06 04:14
@JohannesBeranek, could you check if the merged fix solve your issue. And close the issue if so.

**Comment by xael-fry** [comment] 2022-06-06 15:32
merges #1408

**Closed as completed by xael-fry** 2022-06-06 15:32 UTC
Labels: defect

**Comment by JohannesBeranek** [comment] 2022-06-06 20:45
@xael-fry I'll gladly try the changes once I get around to, but that might not be for some time.
As for the issue about LoggerInit::access see issue #1404
