### ISSUE TITLE
Need to restart Play because **/conf/application.conf has been changed

### ISSUE THREAD

**Issue by crazywhatever** [playframework/play1#1079] opened 2017-01-05 03:49 UTC
just make a new playframework 1.4.3 project, and run it, an exception comes out.

`java.lang.RuntimeException: Need to restart Play because /Users/zhoupeng/Dojo/play-1.4.3-demo/./conf/application.conf has been changed
	at play.ConfigurationChangeWatcherPlugin.onConfigurationFileChanged(ConfigurationChangeWatcherPlugin.java:30)
	at play.ConfigurationChangeWatcherPlugin.detectChange(ConfigurationChangeWatcherPlugin.java:24)
	at play.plugins.PluginCollection.detectChange(PluginCollection.java:598)
	at play.Play.detectChanges(Play.java:641)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at Invocation.HTTP Request(Play!)`

it just came out once when the first request came in, i read the source code and i think in class 

> ConfigurationChangeWatcherPlugin

method detectChange runs before the method onConfigurationRead and when method detectChange runs, it use the property configLastModified which is not initialized correctly.

it seems not a big problem, but kind of annoying.

**Comment by asolntsev** [comment] 2017-01-05 07:34
@crazywhatever Thank you for reporting!
Probably we fixed this problem in branch `1.4.x` (meaning it will be release in play 1.4.x).
Could you try to reproduce this issue with play `1.4.x`?

**Comment by crazywhatever** [comment] 2017-01-05 10:48
@asolntsev yes, it comes out with play 1.4.3

**Comment by romanr** [comment] 2017-01-21 16:46
This is duplicate of #1008 and https://play.lighthouseapp.com/projects/57987/tickets/2065-false-detect-changes-for-applicationconf
Looks like it's fixed for 1.4.4

**Comment by asolntsev** [comment] 2017-02-07 20:20
Yes, this is fixed in play 1.4.4

**Closed by asolntsev** 2017-02-07 20:20 UTC
