### ISSUE TITLE
Documentation for WebSockets should mention PlayController

### ISSUE THREAD

**Issue by spbmssen** [playframework/play1#1207] opened 2017-11-22 11:18 UTC
A web-socket controller that extends `WebSocketController` will not be found by the `ActionInvoker` in 1.5.0 unless it implements the `PlayController` interface, giving unexpected 'No route found' errors.
This is not mentioned in the documentation

**Comment by daohodac** [comment] 2018-02-15 13:52
+1
but @spbmssen why is it necessary? Why WebSocketController does not implement it?

**Comment by greenled** [comment] 2018-04-16 00:27
1.5.0 replaces ControllerSupport with PlayController in ActionInvoker#getActionMethod. This effectively leads to the problem spotted by @spbmssen, as WebSocketController only implements the former.

If this is the intended behavior (and I doubt so, because websocket support in the sample Chat application in 1.5.0 is actually broken, see [this ticket](https://play.lighthouseapp.com/projects/57987/tickets/2165-150-no-route-able-to-invoke-action-websocketchatroomsocketjoin-was-found#ticket-2165-1)), this shoud be documented somewehere. Otherwise, I think fixing it could be as simple as making WebSocketController implement PlayController too, so it is marked as a controller for ActionInvoker.

**Comment by xabolcs** [comment] 2018-08-03 18:39
Should be fixed by commit e55b51b493566e73b6da012f6417907efb433431

**Comment by asolntsev** [comment] 2018-08-04 07:59
@greenled Right, it was a bug. We added `implements PlayController` to all base controllers, but apparently forgot `WebSocketController`.

@xabolcs Thank you for the hint!

@spbmssen Now it should be fixed in Play 1.5.1

**Closed by asolntsev** 2018-08-04 07:59 UTC
